### PR TITLE
Consider yourself endorsed

### PR DESCRIPTION
**Pull request by doismellburning**

### CODE REVIEW

**Comment by DRMacIver** [comment]
:heart:

**Comment by DRMacIver** [comment]
Lol "Pull Requests that have a failing status can’t be merged from a phone". Apparently I can't merge this from the mobile site. Will merge when I'm back at  computer.

**Comment by doismellburning** [comment]
Apparently my endorsement stalled the Python 3.3 build

:metal:

**Comment by DRMacIver** [comment]
It's a travis bug. About half my builds trigger it because of the size of the build matrix :-(

**Pull request merged**
