### PR TITLE
Fix *-imports

### LINKED ISSUE #112: can't use `from hypothesis import *`: Item in ``from list'' not a string
I can't do `from hypothesis import *`. This is because `__init__.py` uses unicode_literals. It seems the only string literals in `__init__.py` are the strings in the `__all__` list, which need to be `str` / `bytes` on python2, so I think it should be safe to just disable that import in that file.

```
radix@伝説:~$ mktmpenv
New python executable in tmp-49ba2df47c475d58/bin/python2.7
Also creating executable in tmp-49ba2df47c475d58/bin/python
Installing setuptools, pip, wheel...done.
This is a temporary environment. It will be deleted when you run 'deactivate'.

(tmp-49ba2df47c475d58)radix@伝説:~/.virtualenvs/tmp-49ba2df47c475d58$ pip install hypothesis
You are using pip version 7.0.3, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting hypothesis
Installing collected packages: hypothesis
Successfully installed hypothesis-1.9.0
(tmp-49ba2df47c475d58)radix@伝説:~/.virtualenvs/tmp-49ba2df47c475d58$ python -c 'from hypothesis import *'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: Item in ``from list'' not a string
```

### PR DESCRIPTION
**Pull request by untitaker**
Fix #112

### CODE REVIEW

**Comment by DRMacIver** [comment]
This won't work as a solution. The imports are enforced as part of the build, and besides this problem exists elsewhere where it's not so easy a fix.

**Comment by untitaker** [comment]
I see. In that case I recommend to avoid usage of unicode_literals completely: https://github.com/PythonCharmers/python-future/issues/22

**Comment by DRMacIver** [comment]
Yeah, that probably is the best solution, it's just a moderate amount of work which I haven't yet felt sufficiently motivated to undertake.

**Comment by untitaker** [comment]
Will take a look.

**Comment by untitaker** [comment]
This PR is finished. As far as I can see it fails for the same reasons as master.

**Comment by DRMacIver** [comment]
I'm not sure why you think this fails for the same reason as master. There are a few flaky tests in master, but all the tests running on python 2 are broken in this PR.

**Comment by DRMacIver** [comment]
Well, rather the morpher tests are broken on python 2 in this PR, so all the builds for python 2 are failing.

**Comment by DRMacIver** [comment]
Here's the problem. You were using raw string literals in the unicode text strategy, which was doing the wrong thing. This patch will fix that: https://gist.github.com/DRMacIver/58dd14c2edf5412e62e5

There are a bunch of other missed bits though. e.g. the test\_simple\_strings test is also failing.

There is a reason why I haven't got around to doing this before now. :-) There are a lot of uses of string literals and most of them need fixing up. I probably wouldn't recommend trying to do this manually and may instead look into using Red Baron to do a fix up.

**Comment by untitaker** [comment]
I did use a regex to remove all future imports, but don't want to replace all raw/native string literals with unicode string literals automatically, because that's what the future import already did and the problems stated in the linked thread would still apply.

It'll take a while before I'll be able to take a look at this PR again.

On 15 August 2015 14:21:15 CEST, "David R. MacIver" <notifications@github.com> wrote:
>Here's the problem. You were using raw string literals in the unicode
>text strategy, which was doing the wrong thing. This patch will fix
>that: https://gist.github.com/DRMacIver/58dd14c2edf5412e62e5
>
>There are a bunch of other missed bits though. e.g. the
>test\_simple\_strings test is also failing.
>
>There is a reason why I haven't got around to doing this before now.
>:-) There are a lot of uses of string literals and most of them need
>fixing up. I probably wouldn't recommend trying to do this manually and
>may instead look into using Red Baron to do a fix up. 
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/DRMacIver/hypothesis/pull/123#issuecomment-131365737

-- 
Sent from my phone. Please excuse my brevity.

**Comment by DRMacIver** [comment]
So I ended up investigating the approach of using redbaron for refactoring and it was actually really easy, so this is now fixed in master. I think this is the correct solution: The only known bug caused by ubiquitous use of unicode literals is the problem with \_\_all\_\_, which is easy to then manually fix up. This keeps the semantics extremely close to what was already happening everywhere.

At any rate, thank you for kicking this work off, and sorry I've ended up going and doing it differently!

**Pull request closed without merging**
