### PR TITLE
Use correct language for code block in docs

### PR DESCRIPTION
**Pull request by inglesp**

### CODE REVIEW

**Comment by DRMacIver** [comment]
This actually isn't a typo. It stands for "python console". It's one of the standard highlights.

**Comment by inglesp** [comment]
Well that's embarrassing!

I did think though that the formatting of eg the code example in http://hypothesis.readthedocs.org/en/latest/data.html#hypothesis.strategies.composite was a little odd -- it's not got the same formatting as other code blocks in the docs.

**Comment by DRMacIver** [comment]
Oops! Yes, that one is using the wrong formatting. Thanks for the catch. I'll fix it.

Basically if there's a >>> in it it should be pycon, otherwise it should be python.

**Comment by DRMacIver** [comment]
Oh, wait, I'm not sure what's going on there. It's not a code block issue, it's that apparently coming from the docstring it gets screwed up.

**Pull request closed without merging**
