### PR TITLE
Allow to provide arguments for fake factories

### PR DESCRIPTION
**Pull request by thedrow**
This allows you to provide the max_nb_chars argument for faker.words() for example.
It's my first contribution to this repository so I might be missing something out.

### CODE REVIEW

**Comment by DRMacIver** [comment]
Thanks for this, @thedrow! Looks like a good idea.

Two problems with it I'd like you to fix first:

1. The lint CI task failed because you've got some lines that are > 80 characters. You need pep8 compliant code. You can run this locally as tox -e lint (this will fail if you have uncommitted changes but will still give you useful errors)
2. Changes require tests to go with them.

As a design comment: I'm not sure having \*args is that useful, because in order to use it you need to explicitly pass the providers args, and I suspect that will mostly end up tripping people up. This might be better as keywords only. What do you think?

**Comment by DRMacIver** [comment]
In fact you need to explicitly pass the locale and locales args, the combination of which is essentially meaningless. I think you might need to stick to passing kwargs only. Is there something important that would prevent?

**Comment by DRMacIver** [comment]
What's the current status of this? Are you planning to look at it again or should I close it?

**Comment by thedrow** [comment]
I'm currently on vacation. Coming back at the 4th of October. Apologies for the delay.

**Comment by DRMacIver** [comment]
Ping. Would you like to revisit this or should I close it?

**Comment by thedrow** [comment]
Let's close this for now. I don't have time to complete it at the moment.

**Pull request closed without merging**
