### PR TITLE
DecimalField support for hypothesis-django

### PR DESCRIPTION
**Pull request by doismellburning**
https://github.com/DRMacIver/hypothesis/issues/87

### CODE REVIEW

**Comment by doismellburning** [comment]
(Sorry, I don't have a working local test environment, so using your CI...)

**Comment by DRMacIver** [comment]
Have you forgotten the commit that does the mapping or are you just doing the world's slowest form of TDD? :-)

(my CI takes a very long time to run and is sadly somewhat unreliable)

**Comment by doismellburning** [comment]
If I didn't observe the test failing, how would I know it was a worthwhile test to add? ;P

(Didn't appreciate the runtime, sorry!)

**Comment by DRMacIver** [comment]
What's the current status of this? The build is failing, but it's also very out of date. Do you want too pick it up again or should I close it?

**Comment by doismellburning** [comment]
Apologies - conflict between my usual style of development ("The CI server will run the tests better than I can, push and fix") and the aforementioned nature of the test suite, combined with lack of time etc.

Will try to Do Something Better, unless you'd rather just close this?

**Comment by DRMacIver** [comment]
I'm perfectly happy to leave it until you have time. I just wanted to check that you did want to come back to it. :-)

**Comment by DRMacIver** [comment]
FWIW there are now django specific tox environments, so you can run ```tox -e django18``` or ```tox -e django17``` to run the tests (the difference is which django version they test against) for local development.

**Comment by doismellburning** [comment]
That sounds awesome, cheers

**Comment by DRMacIver** [comment]
Ping. Would you like to revisit this or should I close it?

**Comment by DRMacIver** [comment]
I'm going to close this. Feel free to reopen it if you want to finish it off later.

**Pull request closed without merging**
