### PR TITLE
Allow varargs when not passing positional arguments (fixes #113)

### LINKED ISSUE #113: Allow varargs when using only keyword arguments
If a test function is wrapped by another decorator, it may be hard to avoid varargs. However, it should still be safe to use `@given` if no positional arguments are used.

I have experimented with this by modifying `run_test_with_generator` to do the following instead of the current vararg check:
```python
        if generator_arguments and original_argspec.varargs:
            raise InvalidArgument(
                'varargs are not supported with positional arguments to @given'
            )
```

`tox -e py26,py27` passes locally for me, so I have reasonable confidence that this doesn't break anything obvious. If you're okay with this change, I'm happy to submit a pull request with the necessary tests and such.

### PR DESCRIPTION
**Pull request by jerith**

### CODE REVIEW

**Comment by jerith** [comment]
I wasn't entirely sure where the new tests should live, so I put them in `tests/cover/test_validation.py` with the only other tests I could find that dealt with `@given` and varargs.

I updated the examples in the docs to include both a correct and an incorrect use of `@given` with varargs. I had to either rename some existing examples or have duplicate function names, so I chose the former.

**Comment by jerith** [comment]
The single Travis failure for the first commit seems to be unrelated to my change.

I *think* the failures on the docs update are also unrelated (I don't see how they could be caused a docs-only change), but there are rather a lot of them for mere chance.

**Comment by DRMacIver** [comment]
The Hypothesis travis build is sadly a little flaky, sorry. :-( Testing Hypothesis itself has a number of issues (when Hypothesis tests other code it's got a no false positives guarantee, but sadly that turns into a lot of false positives on its own build). This is an atypically high number of failures but I'm pretty sure none of these are your fault - one is a known pypy bug and the timeouts sometimes happen when travis is under load. The morphers failure is weird - I've not seen that before - but it basically can't be your bug. It must be a line that I cover with high probability but not 100%.

**Comment by DRMacIver** [comment]
I'm going to kick off a rebuild on travis just to be sure, but assuming that goes green this looks good, thanks.

**Comment by jerith** [comment]
Thanks!

**Pull request merged**
