### PR TITLE
Adds allow_nan/all_infinity to floats()

### LINKED ISSUE #186: Give floats() and decimals() allow_nan and allow_infinity flags.
In order to preserve the current behaviour these should default to True. When set to False, the strategies should not generate NaN or infinite values respectively.

A decent first pass at this would be to just use these flags to filter after the existing generation. It would be good to add these flags to the NastyFloats constructor explicitly though.

decimals() can just pass this through to floats() I think.

### PR DESCRIPTION
**Pull request by moreati**
Part 1 of 2 for #186

### CODE REVIEW

**Comment by DRMacIver** [comment]
Thanks!

Note as per discussion in the other pull request, decimals() should not have allow_nan and allow_infinity added until it also has min_value and max_value, so the signatures can be kept the same.

The appveyor failure isn't your fault and if you rebase off master it's fixed.

**Comment by DRMacIver** [comment]
Also how do you want to handle this as WIP? What you've got so far looks good to merge as is, and a series of small pull requests is generally better.

**Comment by moreati** [comment]
> Also how do you want to handle this as WIP?

I'd missed the part about `decimal(... allow_nan, allow_infinity)` depending on #187. With that cleared up I've amended the title and description.

**Comment by DRMacIver** [comment]
OK. So shall I merge this as is?

**Comment by moreati** [comment]
Yes please (mental note be more explicit)

**Pull request merged**
