### PR TITLE
Add Python 3.2 to the test matrix.

### PR DESCRIPTION
**Pull request by rbtcollins**
(I know this will fail right now, making sure the infra works before looking at what needs fixing).

### CODE REVIEW

**Comment by DRMacIver** [comment]
There are basically two categories of things that need fixing:

1. The object model on Python 3.2 is kinda broken, and this results in some trivial output differences in some place that I historically solved just by not caring.
2. Unicode literals. There is almost no solution to making string literals work sensibly across Python 2 and Python 3.2. unicode\_literals causes a bunch of problems, and not having unicode\_literals causes a bunch of different ones. 3.3 introduced u'' prefixed strings and this made life vastly better.

2 is what caused me to drop 3.2 support as a very bad cost : benefit analysis. I'd personally rather not support it, particularly given the low usage numbers. Do you have a particular use case in mind?

**Comment by rbtcollins** [comment]
Well my use case is pretty simple - I have projects that still support 2.6 and 3.2 (because they're testing projects, so they are the last to migrate really).  I figured I'd poke at it and see how deep the issues went.

One thing I noticed in doing this mechanical patch is that there are a lot of places where strict unicode shouldn't be needed, and I'm not sure why you have it there. I suspect that if unicode was only used where it would trigger implicit encodes of non-ascii unicode strings on 2.x Pythons then the cost would be much lower.

**Comment by rbtcollins** [comment]
That said, I'm ok with not fixing this - its certainly well into diminishing returns space.

**Comment by DRMacIver** [comment]
The reason why I have it there is that they were historically bare literals with unicode_literals turned on and I did a mechanical change using red baron to turn all bare literals into unicode. I would be happy with a change to turn them all back to bare string literals and seeing what breaks.

**Comment by DRMacIver** [comment]
Basically I'm OK with supporting Python 3.2, but it's historically proven rather irritating and is something of a low priority for me. I'm happy to help you make this work though. :-)

**Comment by DRMacIver** [comment]
The verdict on this seemed to be that neither of us were very interested in Python 3.2 support. Do you want to revisit it or should I close this pull request?

**Pull request closed without merging**
